### ISSUE TITLE
Не подгружается файл конфигурации по-умолчанию

### ISSUE THREAD

**Issue by ei-grad** [klen/muffin#10]
Сейчас по-умолчанию muffin не подгружает никакой конфиг (по-умолчанию, это когда не установлена переменная окружения MUFFIN_CONFIG, не передан аргумент muffin --config, и не передан CONFIG при инициализации Application). Было бы неплохо если бы он подгружал config.py как написано в README.md.

**Comment by drgarcia1986** [comment]
I do not agree, you can set the settings as parameters of the application object, so I think wrong to force the existence of a configuration file.

**Comment by ei-grad** [comment]
Почему-то казалось что параметр CONFIG при инициализации приложения должен переопределять переменную окружения, ок, наверно можно забить. Надо только README поправить.
