### ISSUE TITLE
Зачем нужен LStruct?

### ISSUE THREAD

**Issue by ei-grad** [klen/muffin#11]
Кажется что запрет на изменение конфига в runtime это лишнее. Это вряд ли предотвратит большое количество ошибок и выглядит не по питонячьи.

**Comment by klen** [comment]
В отличии от синхронных приложений (Django, Flask) у нас не пересоздается контекст на каждом запросе и изменив что-либо в настройках после старта приложения (фактически при обработке запроса), мы не сможем расчитывать на них при обработке других запросов. Это был один из моих доводов для данной реализации. Я на самом деле не вижу зачем нужно изменять настройки после старта. В любом случае по моему данное ограничение легко обходится если поставить какое либо значение в dict и в дальнейшем менять уже непосредственно его (не проверял, но скорее всего).

Но если у тебя есть аргументированные возражения, то давай обсуждать. «Не по питонячьи» не канает :smile:

**Comment by klen** [comment]
Doesn't actual for version > 0.45
