### ISSUE TITLE
Реализвать метод jsonify

### ISSUE THREAD

**Issue by klinkin** [klen/muffin#2]
1.
Хочется иметь метод jsonify аналог фласковскому 
https://github.com/mitsuhiko/flask/blob/master/flask/json.py#L201

2.
Возможность задать кастомный json.JSONEncoder.
Хотя, как понял, ujson это не поддерживает(

**Comment by klen** [comment]
1. Ну чтобы реализовать поведение по ссылке, ты можешь просто dict возвращать из хендлера и тогда muffin преобразует его в JSON response.

2. Возможно подумаю над этим.

**Comment by ei-grad** [comment]
Про второй пункт это ведь скорее про muffin-rest и преобразование моделей в dict?..

**Comment by klen** [comment]
Doesn't actual for version > 0.45
