### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by nhumrich** [klen/muffin#34]
aiohttp has built in websocket handling.
Since The Muffin is built on top of aiohttp, is should do websockets as well. Is there any exposed way to use websockets with muffin?

**Comment by 0nkery** [comment]
Look at [demonstration](url) from examples.

**Comment by nhumrich** [comment]
Your link doesn't go anywhere that exists. And the example in the readme doesn't show an example for websockets.

**Comment by 0nkery** [comment]
Sorry. Updated.

**Comment by nhumrich** [comment]
Thanks!

**Comment by drgarcia1986** [comment]
I believe not a bug and the issue can be closed

**Comment by klen** [comment]
@drgarcia1986 Agree
