### ISSUE TITLE
Muffin handlers hang when using a Rethinkdb connecton that was made outside of Muffin's loop

### ISSUE THREAD

**Issue by IlyaSemenov** [klen/muffin#36]
For some reason Muffin handlers hang when using a Rethinkdb connecton that was made outside of Muffin's loop. I realise that it isn't necessarily Muffin's fault, but please take a look at the very simple examples below.

**The following script works as expected** (returns "1+1 = 2" on each page load):

```python
import muffin
import rethinkdb as r

r.set_loop_type('asyncio')

app = muffin.Application('example')


@app.register('/')
async def handle(request):
	db = await r.connect()  # <--- Connect every time
	js = '1+1'
	res = await r.js(js).run(db)
	text = "%s = %s" % (js, res)
	return text


if __name__ == '__main__':
	app.manage()
```

**The following script hangs on page load** (and then it dies in long agony on ^C rather than simply quits):

```python
import muffin
import asyncio
import rethinkdb as r

r.set_loop_type('asyncio')

db = asyncio.get_event_loop().run_until_complete(r.connect())  # <--- Connect only once

app = muffin.Application('example')


@app.register('/')
async def handle(request):
	js = '1+1'
	res = await r.js(js).run(db)
	text = "%s = %s" % (js, res)
	return text


if __name__ == '__main__':
	app.manage()
```

I don't think it's purely Rethinkdb problem because **the same approach works with `aiohttp`**:

```python
from aiohttp import web
import asyncio
import rethinkdb as r

r.set_loop_type('asyncio')

db = asyncio.get_event_loop().run_until_complete(r.connect())  # <--- Connect only once


async def handle(request):
	js = '1+1'
	res = await r.js(js).run(db)
	text = "%s = %s" % (js, res)
	return web.Response(body=text.encode('utf-8'))


app = web.Application()
app.router.add_route('GET', '/', handle)

web.run_app(app)
```

**Comment by MarSoft** [comment]
I think this issue may be related to `muffin` (unlike `aiohttp`) being integrated with `gunicorn`. I would try to initialize connection on app init, not on file load:
```
...

app = muffin.Application('example')

@app.register_on_start
async def init_db(app):
    app.db = await r.connect()

@app.register('/')
async def handle(req):
    js = '1+1'
    res = await r.js(js).run(app.db)
    ...
```

As an alternative, I would create separate Muffin plugin for `RethinkDB`, similar to `muffin-peewee` or `muffin-redis`.

**Comment by IlyaSemenov** [comment]
Yes, the `@app.register_on_start` workaround worked (I wonder if there's any documentation where I could learn about it?), but in my opinion it's still better be fixed or documented why it's not possible rather than just getting along with a workaround. Excessive coupling is never good, and might be even impossible in certain circumstances (like using a third party library that is unaware of such idiosyncrasies).

Also, I tried removing `web.run_app(app)` from my pure `aiohttp` example above and running it via `gunicorn` and it still worked fine:

```
(venv) gunicorn test:app --bind localhost:7000 --worker-class aiohttp.worker.GunicornWebWorker
[2016-03-11 12:19:30 +0600] [49040] [INFO] Starting gunicorn 19.4.5
[2016-03-11 12:19:30 +0600] [49040] [INFO] Listening at: http://127.0.0.1:7000 (49040)
[2016-03-11 12:19:30 +0600] [49040] [INFO] Using worker: aiohttp.worker.GunicornWebWorker
[2016-03-11 12:19:30 +0600] [49043] [INFO] Booting worker with pid: 49043
Connected
Handle
Handle
```

So there must be a difference between `aiohttp.worker.GunicornWebWorker` and `muffin.worker.GunicornWorker` that prevents using standalone `asyncio` loop.

**Comment by drgarcia1986** [comment]
I believe not a bug and the issue can be closed

**Comment by klen** [comment]
@drgarcia1986 agree
