### ISSUE TITLE
Продвинутый вариант Class Based View (CBV) 

### ISSUE THREAD

**Issue by klinkin** [klen/muffin#4]
Для тех, кто переезжает с Flask и Pyramid привычно группировать "ручки" в некоторый общий класс. Поэтому предлагаю рассмотреть вариант реализации подобного варианта в Muffin. 
Подробнее в доке https://pythonhosted.org/Flask-Classy.

Кратко хочется такого:
```
class MyCBVHandler(muffin.Handler):
    def get(self, request):
        return {'simple': 'rest', 'example': request.match_info.get('example')}

    def post(self, request):
        return [1, 2, 3]

    @app.register('/random')
    def random(self, request):
        return choice([1, 2, 3])

```

**Comment by klen** [comment]
В текущей архитектуре это тяжело реализовать. В последней версии я добавил возможность сделать так:

```python
class MyCBVHandler(muffin.Handler):
    def get(self, request):
        return {'simple': 'rest', 'example': request.match_info.get('example')}

    def post(self, request):
        return [1, 2, 3]

@MyCBVHandler.register('/random')
def random(handler, request):
    return choice([1, 2, 3])
```

Не совсем тоже самое, но всё таки. При этом random отработает как полноценный метод хендлера, с вызовом handler.dispath и handler.make_response.

**Comment by klinkin** [comment]
Спасибо и на этом :)
Мое небольшое приложение, крутится в проде уже больше месяца!
