### ISSUE TITLE
Use uvloop instead

### ISSUE THREAD

**Issue by peterbe** [klen/muffin#40]
This is full of wonderful hype: http://magic.io/blog/uvloop-blazing-fast-python-networking/

It says it's a drop-in replacement to the `asyncio` main loop that's supposed to be a bit faster. 

Can muffin use this?

**Comment by MarSoft** [comment]
I tried to run Muffin tests while enabling `uvloop` in `conftest.py`, and everything went well.

**Comment by drgarcia1986** [comment]
You can pass any loop to `muffin.Application`:
```python
app = muffin.Application('example', loop=my_uvloop)
```

**Comment by peterbe** [comment]
Yup. Seems to work. However on my mac, benchmarks get slower. So clearly I need to test this somewhere else.

**Comment by 0nkery** [comment]
Wanted to mention - some devs want to add [httptools](https://github.com/MagicStack/httptools) from that post to aiohttp.
WIP is [here](https://github.com/KeepSafe/aiohttp/issues/858).

**Comment by drgarcia1986** [comment]
@peterbe you can look this PR -> #48 and run your benchmarks again (use python 3.5.2 to enable uvloop futures [write in C])

**Comment by peterbe** [comment]
@drgarcia1986 I'd love to but I don' think I'll have time to help.

**Comment by drgarcia1986** [comment]
No problem I try to make some benchs in next days
