### ISSUE TITLE
ACCESS_LOG to syslog

### ISSUE THREAD

**Issue by tanapongr** [klen/muffin#41]
from muffin options

```
#Logging options
'ACCESS_LOG': '-',  # File path to access log, - to stderr
```

Not sure the value is support only file path? or can use some class such as logging.handlers.SysLogHandler(...) ?  

Do you have some example to store access_log to syslog? and is it possible if I store access_log to other server like Graylog?

Thanks,

**Comment by 0nkery** [comment]
I can't test it but you can specify `access_logger` in app parameters. Logger should be compatible with  Python logger objects from `logging` library.

There is [syslog handler](https://docs.python.org/3.5/library/logging.handlers.html#logging.handlers.SysLogHandler) in Python stdlib actually.

Please, try it.

PS. You could make PR that covers this topic in docs. :)

**Comment by tanapongr** [comment]
Ok thanks for reply, let me try and will update again :)
