### ISSUE TITLE
Misleading muffin-mongo description

### ISSUE THREAD

**Issue by touilleMan** [klen/muffin#49]
> Muffin-Mongo -- MongoDB (pymongo) support

[muffin-mongo](https://github.com/klen/muffin-mongo/blob/master/requirements.txt) uses [asyncio-mongo](https://github.com/jettify/asyncio_mongo), this one is a complete rewriting of a mongodb driver from scratch and so has nothing to do with `pymongo`.

I think this point should be clarified like this:

> Muffin-Mongo -- MongoDB (asyncio-mongo) support

**Comment by drgarcia1986** [comment]
If you look for a mongo plugin with "same" api of pymongo try [muffin-motor](https://github.com/drgarcia1986/muffin-motor)
