### ISSUE TITLE
Error: 'django_settings' when trying to execute muffin run

### ISSUE THREAD

**Issue by michaeltcoelho** [klen/muffin#53]
It seems that there's an issue on `GunicornApp` and i'm getting an `Error: 'django_settings'` error whenever i run the `run` command on muffin CLI. 

It seems that the error is on `GunicornApp.load_default_config` in `worker.py`, It's deleting a key in a dict that it does not exist.
 
```python 
del self.cfg.settings['django_settings']
````

I'm using a docker container running a python 3.5 image upon jessie.

I'm running my app by `muffin --config=guidi.dev guidi run`.

Can you guys tell me why there's a key related to django in muffin?

Thanks!

**Comment by michaeltcoelho** [comment]
The hole is further down..

gunicorn has updated to its version 19.7.0 and `django_settings` has been removed, as you can see below:

The previously deprecated `django_settings` setting has been removed. Use the :ref:`raw-env` setting instead. in the [changelog](https://github.com/benoitc/gunicorn/blob/111d0ba7da7b1190cffe55a3d1dfdb748334019f/docs/source/2017-news.rst#id6)

I'll will investigate it and make a pull request!

**Comment by wo0dyn** [comment]
<table>
<tr><th>Python <td>3.5.3<th>Muffin <td>0.10.3
</table>

I had to wipe my virtualenv after an upgrade of python on my machine, and got the same issue.
