### ISSUE TITLE
Question: how to separate urls from views ?

### ISSUE THREAD

**Issue by vlad0337187** [klen/muffin#56]
Is there a standard way to do it ?

I want to separate urls from views just like Django does.
The only way I see not - creating 'urls.py' with list of lists: ['url', 'function_name']

After this importing that urls, importing all functions from views and check name correspondence, if corresponds - simulate @app.register('url_from_urls_py', function_instance).

But, maybe, there is some standard way ?

_Offtop: maybe there are some ready Muffin applications for me to see usage examples ? If yes - give me a link please._

_Offtop 2: if you have vk.com or Telegram account (or, maybe, there is some vk.com group for muffin), and you're not against me to ask you questions there sometimes (as rarely as possible), than give me please contacts._

Thank you.
Best regards,
Vladislav.

**Comment by klen** [comment]
better late than never

```python

# your_project.__init__.py
import muffin

app = muffin.Application()

from .urls import * # noqa

# your_project.urls.py
from your project import app
from your_project.views import index, profile, login, logout

app.route('/', index)
app.route('/profile', profile)
app.route('/login', login)
app.route('/logout', logout)

```
