### ISSUE TITLE
An option to change static files headers?

### ISSUE THREAD

**Issue by f4at** [klen/muffin#70]
Muffin serves the files with the header `"content-disposition: attachment; filename="..."` and that makes the browser download the files instead of displaying them.

**Comment by klen** [comment]
@f4at Hello, thank you for the feedback. I've changed the `ResponseFile` default behaviour, please check the updated docs: https://klen.github.io/muffin/api.html#responsefile-response.

TLDR: For now by default, the `content-disposition` header wouldn't be added.

**Comment by klen** [comment]
`Muffin==0.81.0` is available on pypi
